// <auto-generated />
using System;
using EmpresaDulces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaDulces.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20221109235038_DulcesInfos")]
    partial class DulcesInfos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpresaDulces.Entidades.DulceInfo", b =>
                {
                    b.Property<int>("DulceId")
                        .HasColumnType("int");

                    b.Property<int>("InfoId")
                        .HasColumnType("int");

                    b.Property<int?>("DulcesId")
                        .HasColumnType("int");

                    b.Property<int?>("InformacionDulceId")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("DulceId", "InfoId");

                    b.HasIndex("DulcesId");

                    b.HasIndex("InformacionDulceId");

                    b.ToTable("DulceInfos");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.Dulces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreDelDulce")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Dulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.InformacionDulce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MarcaDeDulce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InformacionDulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("DulcesId")
                        .HasColumnType("int");

                    b.Property<string>("Taste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TasteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DulcesId");

                    b.ToTable("Sabores");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.DulceInfo", b =>
                {
                    b.HasOne("EmpresaDulces.Entidades.Dulces", "Dulces")
                        .WithMany("DulceInfos")
                        .HasForeignKey("DulcesId");

                    b.HasOne("EmpresaDulces.Entidades.InformacionDulce", "InformacionDulce")
                        .WithMany("DulceInfos")
                        .HasForeignKey("InformacionDulceId");

                    b.Navigation("Dulces");

                    b.Navigation("InformacionDulce");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.Sabor", b =>
                {
                    b.HasOne("EmpresaDulces.Entidades.Dulces", "Dulces")
                        .WithMany("Sabores")
                        .HasForeignKey("DulcesId");

                    b.Navigation("Dulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.Dulces", b =>
                {
                    b.Navigation("DulceInfos");

                    b.Navigation("Sabores");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.InformacionDulce", b =>
                {
                    b.Navigation("DulceInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
