// <auto-generated />
using System;
using EmpresaDulces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaDulces.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmpresaDulces.Entidades.Dulces", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreDelDulce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.InformacionDulce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DulceId")
                        .HasColumnType("int");

                    b.Property<int?>("DulcesId")
                        .HasColumnType("int");

                    b.Property<string>("MarcaDeDulce")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DulcesId");

                    b.ToTable("InformacionDulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.InformacionDulce", b =>
                {
                    b.HasOne("EmpresaDulces.Entidades.Dulces", "Dulces")
                        .WithMany("InfoDulce")
                        .HasForeignKey("DulcesId");

                    b.Navigation("Dulces");
                });

            modelBuilder.Entity("EmpresaDulces.Entidades.Dulces", b =>
                {
                    b.Navigation("InfoDulce");
                });
#pragma warning restore 612, 618
        }
    }
}
